services:
  api:
    networks:
      - default
    labels: []

  front:
    ports:
      - "127.0.0.1:5173:5173"
    networks:
      - default
    labels: []

networks:
  proxy:
    name: proxy
    driver: bridge
