services:
  api:
    environment:
      - APP_ENV=dev

  optimizer:
    environment:
      - APP_ENV=dev

  front:
    build:
      target: dev
    volumes:
      - ./front:/app
      - /app/node_modules

